baseurl: '/english/'
permalink: pretty
title: 'Twinai - Building end to end AI healthcare solutions'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/TWINAI-LOGO-MOBILE.jpg"
  desktop: "images/logo/TWINAI-LOGO-512px.jpg"
  desktop_height: "42px"

footer:
  copyright_text: 'Copyright by <a class="Twinai" href="https://www.twinai.tw">www.twinai.tw</a>'

seo:
  meta_og_title: "Twinai - Building end to end AI healthcare solutions"
  meta_og_type: "website"
  meta_og_url: "https://www.twinai.tw"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Twinai is an enterprise AI platform that unlocks the value of your health data.
  We build and license AI modules and create products for a portfolio of clients, including hospitals, insurance, pharma, researchers, clinics, and providers."
  meta_twitter_card: "summary"
  meta_twitter_site: "@twinai"
  meta_twitter_creator: "@twinai"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
