baseurl: '/'
permalink: pretty
title: '智能感知机器人实验室'
lab: 'Intelligent Perception Robotic Lab'

google_analytics_id: ""
baidu_analytics_id: "ed33d03fa163ca0f90c97f458e4659fa"

homepage:
  show_call_box: false

logo:
  #mobile: "images/logo/Logo.png"
  #desktop: "images/logo/Logo.png"
  mobile: "images/logo/logo-mobile.png"
  desktop: "images/logo/logo.png"
  desktop_height: "72px"
  #desktop_height: "36px"

footer:
  copyright_text: '粤ICP备2021094001号</a>'

seo:
  meta_og_title: "智能感知机器人实验室"
  meta_og_type: "website"
  meta_og_url: "https://www.hitsz-robotic.top"
  meta_og_image: ""
  meta_og_description: "哈尔滨工业大学（深圳） 姜欣机器人实验室"
  # meta_twitter_card: "summary"
  # meta_twitter_site: "@zerostaticio"
  # meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
