# site settings

title: Daniel Micallef
description: Python . Sports . Healthy Food and Coffee!
taglong: Making life easier with Python and harder with barbells and dumbells.
tagshort: Daniel's CV
url: https://danielmicallef.xyz
baseurl: ""
permalink: pretty
repo: https://github.com/danielMicallef/xyz.github.io

# author settings

author:
  name: Daniel Micallef
  email: danielmicallef94@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  # facebook: username
  github: danielMicallef
  # instagram: username
  linkedin: daniel-micallef
  stackoverflow: 4222959/daniel-micallef
  twitter: micallef_daniel

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
