# docker-compose.yml
version: '3.9'
services:
  jekyll:
    build: .
    command: >
      bash -c "bundle exec jekyll serve --host 0.0.0.0 --trace"
    ports:
      - "4000:4000"
    volumes:
      - "./src:/srv/jekyll"
