name: Build Jekyll and Deploy to Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Rubyをセットアップします。
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1 # 3.8.0は存在しないバージョンです, 3.0など正しいバージョンを指定してください。

      # Jekyllと依存関係をインストールします。
      - name: Install Jekyll and dependencies
        env:
          JEKYLL_VERSION: 3.8.0
        run: |
          gem install bundler jekyll
          bundle install

      # Jekyll サイトをビルドします。
      - name: Build Jekyll site
        run: |
          cd jekyll-serif-theme/src
          bundle exec jekyll build

      # Azure にビルドされたサイトをデプロイします。
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MOSS_085CF2E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "jekyll-serif-theme/src/_site" # ビルドされたJekyll サイトの位置を修正
          api_location: ""
          output_location: "/"
